### PR TITLE
Get comments from Involvment API

### PR DESCRIPTION
**Pull request by jaferIdrees**
**On this Branch I did the below features**

- When comments PopUp displays, the comments fetched from the Involvement API and added to the PopUp

### CODE REVIEW

**Review by Alzubair98 — CHANGES_REQUESTED** [review]
Hi @jaferIdrees 

you are doing great but i think you have missed small detail about the requirements
comments


in the image above you can see that when i press on any comment button i got all the comments 
while the requirement is  to get only the book comments. kindly fix it

please contact me if you have any questions

**Comment by jaferIdrees** [comment]
Hi @Alzubair98

I'm not sure if I get your point that when you open any book comments popup you get the comments for all books?
I tested it and got different comments count for each book

**Comment by Alzubair98** [comment]
Hello jafer
Maybe its some mistake from my side
I will check it again tomorrow

**Comment by Alzubair98** [comment]
hi @jaferIdrees 

APPROVED 
there is nothing to do more 
just merge it

**Review by Alzubair98 — APPROVED** [review]

**Pull request merged**
